server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

nextmall:
  identifier:
    node-id: ${NODE_ID}

token:
  passport:
    secret-key: ${TOKEN_PASSPORT_SECRET}
