spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false

integration:
  user:
    base-url: http://localhost:8080
  auth:
    base-url: http://localhost:8080
