server:
  port: 8082

spring:
  application:
    name: bff-service

token:
  passport:
    secret-key: ${TOKEN_PASSPORT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}]"
