server:
  port: 8082

spring:
  application:
    name: bff-service

client:
  user:
    base-url: http://localhost:8083
  auth:
    base-url: http://localhost:8081
  product:
    base-url: http://localhost:8084
  order:
    base-url: http://localhost:8085
  orchestrator:
    base-url: http://localhost:8087

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

token:
  passport:
    secret-key: ${TOKEN_PASSPORT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
  tracing:
    sampling:
      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY}
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}]"
