[versions]
jib = "3.5.2"
jooq-plugin = "10.2"
karate = "1.5.2"
kotest = "6.0.7"
kotest-spring = "6.0.7"
ktlint = "14.0.1"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
liquibase = "5.0.1"
logback = "1.5.24"
mockk = "1.14.7"
postgresql = "42.7.8"
redis-testcontainers = "2.2.4"
sonarqube = "7.2.2.6593"
spring-boot = "4.0.1"
spring-cloud = "2025.1.0"
spring-dependency-management = "1.1.7"
springmockk = "5.0.1"
testcontainers = "2.0.3"

[plugins]
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
jooq-plugin = { id = "nu.studer.jooq", version.ref = "jooq-plugin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[libraries]
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
karate-junit5 = { module = "com.intuit.karate:karate-junit5", version.ref = "karate" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest-spring" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
spring-boot = { module = "org.springframework.boot:spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aspectj" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-data-redis-test = { module = "org.springframework.boot:spring-boot-starter-data-redis-test" }
spring-boot-starter-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-boot-starter-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webclient = { module = "org.springframework.boot:spring-boot-starter-webclient" }
spring-boot-starter-webclient-test = { module = "org.springframework.boot:spring-boot-starter-webclient-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-webtestclient = { module = "org.springframework.boot:spring-boot-webtestclient" }
spring-cloud-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
spring-cloud-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway-server-webflux" }
spring-context = { module = "org.springframework:spring-context" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-core = { module = "org.testcontainers:testcontainers"}
testcontainers-junit5 = { module = "org.testcontainers:testcontainers-junit-jupiter"}
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql"}
testcontainers-redis = { module = "com.redis:testcontainers-redis", version.ref = "redis-testcontainers"}
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
