server:
  port: 8084

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

nextmall:
  identifier:
    node-id: ${NODE_ID}

token:
  service:
    secret-key: ${TOKEN_SERVICE_SECRET}
