server:
  port: 8080

spring:
  application:
    name: nextmall-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
  token-prefix: "Bearer "

nextmall:
  identifier:
    node-id: ${NODE_ID}