server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

nextmall:
  identifier:
    node-id: ${NODE_ID}

token:
  service:
    secret-key: ${TOKEN_SERVICE_SECRET}
