server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI}

token:
  passport:
    secret-key: ${TOKEN_PASSPORT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  tracing:
    sampling:
      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}

gateway:
  security:
    permit-all-paths:
      # Auth / Public APIs
      - /api/v1/auth/login
      - /api/v1/sign-up/**
      - /api/v1/auth/tokens/refresh

      # JWKS endpoint
      - /.well-known/jwks.json

      # Health check
      - /actuator/health
      - /actuator/info

      # Spring
      - /error

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}]"
