server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

token:
  passport:
    secret-key: ${TOKEN_PASSPORT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

gateway:
  security:
    permit-all-paths:
      # Auth / Public APIs
      - /api/v1/auth/login
      - /api/v1/sign-up/**
      - /api/v1/token/refresh

      # JWKS endpoint
      - /.well-known/jwks.json

      # Health check
      - /actuator/health
      - /actuator/info

      # Spring
      - /error
