server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

gateway:
  security:
    permit-all-paths:
      - /api/v1/auth/login
      - /api/v1/sign-up/**
      - /api/v1/token/refresh
      - /health
      - /actuator/**
